### ISSUE TITLE
Merge an array in a json

### ISSUE THREAD

**Issue by planemad** [trentm/json#102]
Input

```
{"type":"items","item":[1,2]}
{"type":"items","item":[2,4]}
```

Expected output

```
{"type":"items","item":[1,2,2,4]}
```

Neither `-g` and `--merge` give the expected output. Is this even possible currently?

**Comment by trentm** [comment]
Sorry for the crazy delay. `json` isn't that well suited here, but here is one way: ```
$ echo '{"type":"items","item":[1,2]}
{"type":"items","item":[2,4]}' | json -gAe 'top=this[0]; for (i=1; i<this.length; i++) { top["item"] = top["item"].concat(this[i]["item"]) };' 0
{
  "type": "items",
  "item": [
    1,
    2,
    2,
    4
  ]
}
```
