### ISSUE TITLE
Manpage installs into wrong place

### ISSUE THREAD

**Issue by ukch** [trentm/json#107]
I am using nvm. When I install this package `npm install -g json`, the manpage installs into `~/.nvm/versions/node/whatever/lib/node_modules/json/man/man1/`, but it probably ought to install into `~/.nvm/versions/node/whatever/share/man/man1/`.

**Comment by trentm** [comment]
Published json@9.0.6 with this. @ukch Sorry for the crazy delay. Are you (or anyone else) able to confirm if this works with nvm now? It works for me with `npm install -g json`.

**Comment by ukch** [comment]
Sorry for the delay @trentm. I can confirm that this now works as expected.
