### ISSUE TITLE
Usage of json command from crontab

### ISSUE THREAD

**Issue by alessandro43** [trentm/json#109]
I'm using the javascript json command on Ubuntu to manipulate some .json files.
All works perfectly when I execute the command from the bash prompt or when the command is included in a shell script executed from the bash prompt. But when I execute the same script (including the json command) from the crontab, the command fails because  the necessary environment (#!/usr/bin/env node) is not set. How the problem can be solved?

**Comment by trentm** [comment]
I'm guessing that is the case because in the limited environment in which cron is run, that wherever you have `node` installed is not on the PATH. You could explicitly add that to your crontab line, something like:

```
3 * * * * PATH=/path/to/my/node/bin:$PATH json --version >>/var/tmp/cron-test.log 2>&1
```

Or you could change the first line of your installed "json" script to:

```
#!/path/to/my/node/bin/node
```
