### ISSUE TITLE
How reasonable would it be to ask/add support for json with comment? 

### ISSUE THREAD

**Issue by amotzte** [trentm/json#126]
I know that historically json doesn't support comments ```//``` ```/*...*/```
But today I've seen it being used in many node.js application (BTW json5 does support it officially). I need it in order to edit config file  (https://www.npmjs.com/package/config) from cmd which might contains some comments.

**Comment by trentm** [comment]
@amotzte Thanks for asking. My opinion is that this should be done in a separate tool, perhaps called `json5`.
