### ISSUE TITLE
Cannot set a value for a key with a period

### ISSUE THREAD

**Issue by andymartinwork** [trentm/json#143]
`echo '{"foo.bar": 42}' | npx json -e 'foo.bar="baz"'`

ReferenceError: foo is not defined

`echo '{"foo.bar": 42}' | npx json -e 'foo\\.bar="baz"'`

Invalid or unexpected token

`echo '{"foo.bar": 42}' | npx json -e '["foo.bar"]="baz"'`

Invalid destructuring assignment target

**Comment by trentm** [comment]
@andymartinwork  You'll need to do something like this:

```
% echo '{"foo.bar": 42}' | npx json -e 'this["foo.bar"]="baz"'
{
  "foo.bar": "baz"
}
```
