### ISSUE TITLE
Consider merging a csv output tool

### ISSUE THREAD

**Issue by mrjcleaver** [trentm/json#86]
E.g. https://github.com/zemirco/json2csv because https://github.com/zemirco/json2csv/issues/26
or https://github.com/matteofigus/nice-json2csv

There are plenty:
https://github.com/search?l=JavaScript&q=json2csv&type=Repositories&utf8=✓

Thanks, M.

**Comment by trentm** [comment]
No thank you. I want `json` to be a single file with no external deps. It should be easy enough for one to pipe json output from `json` through a separate `json2csv` tool.

**Comment by mrjcleaver** [comment]
Ok. Actually maybe I missed it - we can export as CSV seemingly with -d, that might be enough!

Will get back if not. Thanks.
