### ISSUE TITLE
-a not outputting intended iterable array

### ISSUE THREAD

**Issue by mistakevin** [trentm/json#91]
```
#example.json
{
    "arr": [
        {
            "a": "foo1",
            "b": "bar1"
        },
        {
            "a": "foo2",
            "b": "bar2 bar2"
        }
    ]
}
```
`json -f example.json | json arr | json -a a b`
outputs as intended:
```
foo1 bar1
foo2 bar2 bar2
```
yet
```
ARR=$(json -f example.json | json arr | json -a a b)

for ITEM in $ARR
do
    echo $ITEM
done
```
outputs:
```
foo1
bar1
foo2
bar2
bar2
```
How do I set the captured output in the last example as the intended iterable array?

**Comment by chorrell** [comment]
This isn't related to `json -a`. You need to explicitly save the output as array in bash:

```
$ ARR=( $(json -f example.json | json arr | json -a a b) )
```
And then reference the var as an array:

```
$ echo ${ARR[*]}
foo1 bar1 foo2 bar2 bar2
```
See:
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_10_02.html

**Comment by chorrell** [comment]
(Using bash as an example)

**Comment by mistakevin** [comment]
That also didn't work for me, as it is again space-delimited every string into its own item `['foo1', 'bar1', 'foo2', 'bar2', 'bar2']` What I'm looking for is
```
[ 'foo1 bar1', 'foo2 bar2 bar2']
```
I was finally able to accomplish with
```
json -f example.json | json arr | json -a a b | while read ITEM
do
    echo $ITEM
done
```

**Comment by trentm** [comment]
Yup, using bash `while` is how I do this. Some perhaps helpful notes here: http://stackoverflow.com/questions/10929453/bash-scripting-read-file-line-by-line
