### ISSUE TITLE
How to merge json from stdout into file in place?

### ISSUE THREAD

**Issue by asmod3us** [trentm/json#95]
Is it possible to merge json read from stdin into a file in place?
With the following test data
```
echo '{ "foo": 1 }' > foo.json; echo '{ "bar": 2 }' > bar.json
```
my attempt to merge bar into foo with
```

json -I --merge -f foo.json < bar.json
```
seems to leave foo.json untouched except for formatting. Is this possible somehow with `json`?

**Comment by trentm** [comment]
Unfortunately, not currently no. `json` doesn't current support pulling its data from more than a single source (stdin *or* a file).
