### ISSUE TITLE
Question: Can I push into an array?

### ISSUE THREAD

**Issue by reggi** [trentm/json#98]
I have a json file like this:

``` json
{
  "babel": {
    "presets": [
      "chicken"
    ]
  }
}
```

I'd like to be able to add `cow` to the presets array if it exists and if the structure isn't there, then just have the array with `cow`, is this possible?

Here's my sad attempt.

```
json -I -f package.json -e 'this.babel={}' -e 'if (typeof this.babel.presets === 'undefined') this.babel.presets=[]' -e 'this.babel.presets.push("chicken")'
```

**Comment by marcofranssen** [comment]
+1 for this question I'm trying to do the same for updating an array.

My sad attempt using merge doesn't work.

```bash
#!/bin/bash

for file in ./the_files/* ; do
    version="`echo $file | sed -re "s@^${name}_([.0-9]+)@\1@g"`"
    version_json="{ \"version\":\"$version\",\"file\":\"$file\" }"
    tmp_json=/tmp/$name.version.$version.json
    echo "{\"versions\": [$version_json] }" | json -o json-4 > $tmp_json
done

catalog=my_versions.json
cat $catalog \
        /tmp/$name.version.*.json \
        | json --merge -I -f $catalog
```

What I try to do is update the existing my_versions.json with the new files added in the `the_files` folder.

**Comment by marcofranssen** [comment]
@reggi https://github.com/trentm/json/issues/92 this is how you can do it... forgot I did this in the past.

However for my own question I do want to have that --merge working

**Comment by trentm** [comment]
Thanks for answering the original Q @marcofranssen. It has been a long while, so I'll assume you found out some solution for your second Q. If not, please open a new ticket for it. Thanks!
